server:
  port: 8001

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: config
  security:
    user:
      name: root
      password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      port: 35731

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:8000/eureka/

logging:
  level:
    root: info
