server:
  port: 8000

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: eureka
  security:
    user:
      name: root
      password: root

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:8000/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    root: info
