server:
  port: 8002

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      port: 35733

eureka:
  instance:
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://root:root@${spring.cloud.client.ip-address}:${server.port}/eureka/

logging:
  level:
    root: info
